### ISSUE TITLE
NHN Cloud Log&Crash

### ISSUE THREAD

**Issue by yrrho2** [nhnacademy-be5-staff99/store99-ect#16]
NHN Cloud Console의 Data&Analytics에서 Log &Crash Search를 사용합니다.
Log & Crash Search는 조직-프로젝트에서 사용합니다. 
NhnAcademy 5기는 NHN Academy - 대전-BE-5 프로젝트에서 다른팀과 앱을 공유합니다.
URL&Appkey에서 Appkey를 앱의 식별자로 사용합니다. 외부에 노출이 되지 않아야합니다.

Log N Crash를 사용하기 위해서 프로젝트에 다음 SDK의 의존성을 pom.xml에 적용해야합니다.
Java Spring을 사용하는 이 프로젝트에서는 Java Logback SDK를 사용합니다.
[https://docs.nhncloud.com/ko/Download/](url)

프로젝트의 pom.xml에 다운로드 받은 SDK을 적용하는 2가지 방법이 있습니다.
```
<dependency>
	<groupId>nhn.logncrash</groupId>
	<artifactId>toast-logncrash-logback-sdk</artifactId>
	<version>3.0.5</version>
	<scope>system</scope>
	<systemPath>
		${project.basedir}/src/main/resources/libs/toast-logncrash-logback-sdk-3.0.5.jar
	</systemPath>
</dependency>
```
pom.xml에 추가하여 resources에 있는 libs폴더에 저장된 sdk을 사용하면 인텔리제이 build에서 로그를 보낼 수 있습니다.
하지만 이 방법은 mvn빌드시 jar파일이 누락되어 원활한 배포가 진행되지 않습니다.
그래서 다음의 방법으로 SDK를 추가합니다.

pom.xml에 다음의 코드를 추가합니다.
```
<repositories>
	<repository>
		<id>logncrash</id>
		<url>file:\\${project.basedir}\src\main\resources\libs</url>
	</repository>
</repositories>
```
```
<dependency>
	<groupId>nhn.logncrash</groupId>
	<artifactId>toast-logncrash-logback-sdk</artifactId>
	<version>3.0.5</version>
</dependency>
```
pom에 로컬 레포지토리를 만들기위해 다음사진과같이 경로를 만들어줍니다.
`groupId/artifactId/version/jar이름`
![Image](https://github.com/nhnacademy-be5-staff99/store99-ect/assets/86106442/365b8c40-d03b-42cb-a9fd-416b7926aed8)
이 방법을 사용하면 mvn build에서도 sdk를 포함하여 배포할수 있습니다.

NHN에서 제공한 SDK를 사용하여 NHN Cloud LogNCrash를 사용합니다.
resources에 개발(dev)버전과 (prod)버전을 나누어 로그를 출력-전송 할 수 있습니다.
application-{profile-active}.properties에
`'logging.config=classpath:logback-{profile-active}.xml`
을 추가하여 원하는 log 출력-전송 방법을 설정할수있습니다. profile-active는 파라미터 입력으로 dev와 prod등이 될수있습니다.

logback-{profile-active}.xml파일에서 콘솔과 nhn logNcrash로 로그를 전송하는 방법입니다.
```
<configuration>
    <conversionRule conversionWord="clr" converterClass="org.springframework.boot.logging.logback.ColorConverter" />
    <appender name="CONSOLE" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %clr(%-5level) %cyan(%logger) - %msg%n</pattern>
        </encoder>
    </appender>
    <root level="DEBUG">
        <appender-ref ref="CONSOLE"/>
    </root>
</configuration>
```
root에 CONSOLE이라는 name을 가진 콘솔입력을 추가하여 프로젝트가 콘솔에서 설정된 level수준이상의 로그를 출력합니다.

```
<!-- LogNCrashHttpAppender 선언 -->
    <appender name="logNCrashHttp" class="com.toast.java.logncrash.logback.LogNCrashHttpAppender">
        <param name="appKey" value="${LOG_N_CRASH_APP_KEY}"/>
        <param name="logSource" value="${spring.profiles.active}"/>
            <param name="category" value="store99-front:8080"/>
    </appender>
    <!-- LogNCrashHttpAppender를 포함한 AsyncAppender 선언 -->
    <appender name="LNCS-APPENDER" class="ch.qos.logback.classic.AsyncAppender">
        <!-- Logback의 AsyncAppender 옵션 -->
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>INFO</level>
        </filter>
        <includeCallerData value="false"/>
        <queueSize value="2048"/>
        <neverBlock value="true"/>
        <maxFlushTime value="60000"/>
        <appender-ref ref="logNCrashHttp"/>
    </appender>
    <root level="INFO">
        <appender-ref ref="LNCS-APPENDER"/>
    </root>
```
요청의 내용을 설정하고  로그 level과 size등을 설정하여 전송합니다. 
이때, ${LOG_N_CRASH_APP_KEY}에는 nhn URL&Appkey의 Appkey를 넣어주어야합니다. 
코드상에 키를 직접 입력하면 보안상의 위험이 있어 실행 VM option에 다음을 추가하여 실행합니다.
`-DLOG_N_CRASH_APP_KEY=진짜 키 내용`

xml파일들을 설정하고 빌드를 수행하면 기존의 로그들은 nhn logncrash로 전송되어 로그의 내용들이 포함된 정보를 저장, 검색 할 수 있습니다. 카테고리와 host으로 로그를 전송한 인스턴스와 기능을 구별할수있습니다.

**Comment by seung-gyu-kim** [comment]
키햐! 갓동영 Working Young!

**Comment by Rosin23** [comment]
읽기 전 추천!
