### ISSUE TITLE
인증/인가 (로그인 및 Token 발급 Flow)

### ISSUE THREAD

**Issue by SongAhyeon01** [nhnacademy-be5-staff99/store99-ect#34]
# Login Sequence

```mermaid

sequenceDiagram

actor c as Client
participant front as Front
participant redis as Redis
participant gateway as Gateway
participant auth as Auth
participant store as BookStore

c->>front: 1. 로그인 페이지 요청
front-->>c: 2. 로그인 페이지 응답
c->>front: 3. Email, PW 입력
front->>gateway: 4. 로그인 요청
gateway->>auth: 4. 로그인 요청
auth-->>gateway: 5. 로그인 api 호출
gateway->>store: 5. 로그인 api 호출
alt 로그인 실패
	store-->>gateway: 6. 회원 정보 없음 or ID/PW 불일치
	gateway->>auth: 6. 회원 정보 없음 or ID/PW 불일치
	auth-->>gateway: 7. 로그인 실패
	gateway-->>front: 7. 로그인 실패
	front-->>c: 7. 로그인 실패
else 로그인 성공
	store-->>gateway: 6. 로그인 성공 & 구매자 id 전달
	gateway->>auth: 6. 로그인 성공 & 구매자 id 전달
	auth-->>redis: 7. UUID 저장
    Note over auth: AccessToken 생성
    auth-->>gateway: 8. Header 에 AccessToken 담아서 전달
    gateway-->>front: 9. Header의 Set-Cookie 에 Token 담아서 전달
    front-->>c: 9. 로그인 성공, 쿠키 전달
end

```

# Authorization Sequence

> 예시 : 마이페이지 요청

```mermaid

sequenceDiagram

actor c as Client
participant front as Front
participant redis as Redis
participant gateway as Gateway
participant auth as Auth
participant store as BookStore

c->>front: 1. `X-USER-TOKEN` 쿠키를 포함하여 마이페이지 요청
front->>+gateway: 2. `X-USER-TOKEN` 헤더를 포함하여 마이페이지 요청
Note over gateway: 토큰 만료 여부 확인
alt 토큰 만료
    gateway-->>front: 3. 인증 실패
    front-->>c: 4. 권한 없음 ERROR 페이지 리다이렉트
else 토큰 사용 가능
    gateway-->>redis: 3. UUID 로 구매자 id 조회
    redis->>gateway: 4. 구매자 id 전달
    gateway->>store: 5. header에 구매자 id 담아 마이페이지 api 호출
    Note over store: 구매자 id 로 회원 권한 조회
    alt 권한 없음
        store-->>gateway: 6. 요청 실패 응답
        gateway-->>front: 6. 요청 실패 응답
        front-->>c: 7. 권한 없음 ERROR 페이지 리다이렉트
    
    else 권한 있음
        store-->>gateway: 6. 회원 정보 전달
        gateway-->>front: 6. 회원 정보 전달
        front-->>c: 7. 마이페이지 응답
    end
end

```

---

# Local 환경에서 테스트
## 사전 준비
테스트용 개인 DB에 DDL 로 테이블 생성 후 user 정보를 DML 로 입력합니다.
[비밀번호 bcrypt 암호화는 이 사이트를 이용하면 편리합니다 >](https://bcrypt-generator.com)

```sql

> user_id(consumer_id) 를 제외하고는 모두 임의로 변경해도 됩니다. 비밀번호 변경 시 꼭 bcrypt 암호화를 해야합니다.

INSERT INTO users(user_id, user_birthdate, grade_id, user_login_at, user_is_inactive, created_at, auth_id, user_point) VAlUES(1, "2022-01-01", 1, "2022-01-01", 0, "2022-01-01", 1, 10000);
INSERT INTO consumers(consumer_id, consumer_name, consumer_email, consumer_phone, consumer_password) VALUES(1, "ahyeon", "ahyeon@naver.com", "01012345678", "1234");
INSERT INTO auths(auth_id, auth_name) VALUES(1, "USER");
INSERT INTO auths(auth_id, auth_name) VALUES(2, "ADMIN");
INSERT INTO grades(grade_id, grade_name, grade_start_cost, grade_end_cost, grade_ratio) VALUES(1, "BASIC", 1000, 10000, 10);

UPDATE consumers SET consumer_password = "$2a$12$rKbLkepB7hmeAnZKlk45gOUb7LHwpw6.7NMrCHMkuB.q1jHegXrki" WHERE consumer_id = 1;
```

## 테스트용 환경 구성
1. ID (Email) : 개인 DB 에서 설정한 user 의 Email
2. PW : 1234 (DB 에 넣을 때는 꼭 bcrypt 인코딩이 되어야 합니다.)
3. user_id (consumer_id) : 1
4. REDIS UUID : c837592c-303b-40f1-9387-7fdc32483a58 (value : 1, 만료 : 2024년 6월 30일)
5. JWT 토큰 : 
BearereyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJVVUlEIjoiYzgzNzU5MmMtMzAzYi00MGYxLTkzODctN2ZkYzMyNDgzYTU4IiwiaWF0IjoxNzEzMTE3MTA5LCJleHAiOjE3MTk3OTE5OTl9.91t59q13KwP9wPk1PI2voWqu0v6Gqspof9jpbrf0JcA (만료 : 2024년 6월 30일)

![Image](https://github.com/nhnacademy-be5-staff99/store99-ect/assets/114563915/ce5a1076-378e-42af-a6bf-24881bf36fea)

---

# 인증 / 인가 상세 로직
## 로그인
1. `localhost:8080/login_form` 으로 들어갑니다.
2. DB에 넣은 user 의 정보에 맞게 로그인 폼을 작성합니다.
3. 로그인 성공 시 `X-USER-TOKEN` Cookie 가 발급되며, index 페이지로 리다이렉트 됩니다.
4. 로그인 실패 시, 로그인 창에서 alert 로 로그인 실패 메세지가 뜹니다.

### 😃 로그인 성공
![image](https://github.com/nhnacademy-be5-staff99/store99-front/assets/114563915/77a74950-9434-4ce3-b315-e993df73da30)

### 🚫 로그인 실패
![image](https://github.com/nhnacademy-be5-staff99/store99-front/assets/114563915/d5a728a7-aa0c-4f93-8b34-bb607969e3ff)

## 토큰 검사
토큰 검사는 front 에서 /api 경로로 요청 시 gateway filter 를 통해 수행됩니다.
### 1. front 에서 feign client 등을 이용해 `/api/bookstore/**` 로 api 요청을 보냅니다. (X-USER-TOKEN 헤더 포함)

> **쿠키 -> 헤더**
> 
>    1-1. front server 에서 특정 경로의 controller 호출 시 CookieAddInThreadLocalInterceptor 가 동작하여 ThreadLocal 에 쿠키 저장 (쿠키 관리가 필요한 ( /api 요청에 사용되는) controller 추가 시 `addPathPatterns` 에 경로를 추가하세요)
> ```java
> 
> registry.addInterceptor(new CookieAddInThreadLocalInterceptor()).addPathPatterns("/books/**", "/mypage/**, /logout");
> 
> ``` 
>    1-2. `FeignConfig` 설정에 따라 `${gateway.url}/api/bookstore` 로 다른 서버 호출 시 interceptor 가 동작하여 ThreadLocal 에서 X-USER-TOKEN 을 찾아 header 에 추가
> 
> ```java
> 
> <예시>
> 
> @FeignClient(value = "store99-gateway-service", url = "${gateway.url}/api/bookstore/v1/mypage") 
> public interface MypageAdaptor { 
>
> @GetMapping("/like") 
> ResponseEntity<CommonResponse > getMyPageInfo(@RequestHeader("X-USER-TOKEN") String xUserToken);
>  }
> 
> ```

### 2. gateway 에서 토큰을 검사합니다
- `X-USER-TOKEN` 이라는 이름의 header 가 있는 지 확인
- 토큰 값이 비어있는 지 확인
- 토큰이 만료되었는 지 확인
- UUID 에 해당하는 userId 존재하는 지 확인
<br>

- 토큰 검사에 실패할 경우 401 Error 를 반환하고, front 에서는 이를 받아 unauthorized page 를 표시합니다.

### 4. bookstore server 에서는 header 중 `X-USER-ID` 가 있는 지 확인하고, userId 값에 따라 적절한 처리를 합니다.
- userId 가 실제 DB 에 존재하는 지 확인 할 수 있습니다.
- userID 가 USER 권한을 가지고 있는 지 확인 할 수 있습니다.

### 5. bookstore 에서 CommonResponse 형식에 맞게 값을 전달하면 front 에서 적절히 처리합니다.

# 테스트 예시
front 는 아직 controller 구성이 되어있지 않아, gateway 에 직접 접속했습니다.
1. `X-USER-TOKEN` header 에 JWT token 을 담아 `/api/bookstore/v1/books` 요청

### 😀 성공 시
![Image](https://github.com/nhnacademy-be5-staff99/store99-ect/assets/114563915/a08848fa-8145-4457-b35c-b94ca7e41da3)

### 🚫 실패 시
- jwt 토큰의 만료 기간을 현재보다 이전으로 하여 훼손

![Image](https://github.com/nhnacademy-be5-staff99/store99-ect/assets/114563915/f3db5e4f-5914-4e4b-982d-96033ca67a84)

- header 에 `X-USER-TOKEN` 을 포함하지 않음

![Image](https://github.com/nhnacademy-be5-staff99/store99-ect/assets/114563915/db341cc0-263f-445c-a169-43ab61318e9f)

**Comment by seung-gyu-kim** [comment]
BearereyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhY2Nlc3MtdG9rZW4iLCJVVUlEIjoiYzgzNzU5MmMtMzAzYi00MGYxLTkzODctN2ZkYzMyNDgzYTU4IiwiaWF0IjoxNzEzMTE3MTA5LCJleHAiOjE3MTk3OTE5OTl9.91t59q13KwP9wPk1PI2voWqu0v6Gqspof9jpbrf0JcA 토큰을 이용하면 401 ERROR UNAUTHORIZED가 뜹니다. 이제 사용 못하나요? # @SongAhyeon01

**Comment by SongAhyeon01** [comment]
어엇.. redis 에서 uuid 가 사라진걸까요.. gateway 로그에 어떤 에러라고 떴나요??

**Comment by seung-gyu-kim** [comment]
> 어엇.. redis 에서 uuid 가 사라진걸까요.. gateway 로그에 어떤 에러라고 떴나요??

2024-04-16 19:20:43.473 [reactor-http-nio-3] DEBUG com.nhnacademy.store99.gateway.filter.AuthorizationFilter - userId 가 존재하지 않음
라고 뜨네요!
